apiVersion: v1
kind: ServiceAccount
metadata:
  name: grpc-server
  namespace: federation-autoscaler-system
  labels:
    app.kubernetes.io/name: federation-autoscaler
    app.kubernetes.io/component: grpc-server
