apiVersion: broker.federation-autoscaler.io/v1alpha1
kind: Reservation
metadata:
  labels:
    app.kubernetes.io/name: federation-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: reservation-sample
spec:
  # TODO(user): Add fields here
