#!/usr/bin/env python3
"""
pgfplotsWriter.py
=================

Shared LaTeX output for the chart scripts: every figure they draw is also
written as `pgfplots` source, so a thesis can carry the vector figure itself
rather than a PNG of it, and retouch size, font and colours by hand.

The code is generated from the numbers, not converted from the matplotlib
figure. For these charts that is the better trade: a step curve is
`const plot`, a band is two paths and a `fill between`, a boxplot is
`boxplot prepared` -- a handful of readable lines each, instead of a
machine-made dump nobody can edit. (`tikzplotlib`, which does the conversion,
has been archived since 2023 and does not work with current matplotlib.)

Not a command-line tool: it is imported by ecoDiagramMaker.py,
latencyDiagramMaker.py and phaseBoxplotMaker.py.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

# The palette the PNGs use, so the two versions of a figure are the same
# figure. Names are the LaTeX colour names declared in every generated file.
COLOURS = {
    "phaseRandom": "C0392B",
    "phasePolicy": "1E8449",
    "phaseFloor": "A8862C",
    "phaseBand": "D9C37A",
    "phaseOutlier": "888888",
}


def escape(text: str) -> str:
    """Escapes what these labels can actually contain -- a percent sign, an
    underscore, an ampersand -- and turns a topology label into proper LaTeX
    multiplication."""
    out = text.replace("&", r"\&").replace("%", r"\%")
    out = out.replace("_", r"\_").replace("#", r"\#")
    if out[:1].isdigit():
        return out.replace("x", r"$\times$")
    # The one unit in these figures that deserves a subscript in a thesis.
    return out.replace("gCO2eq", r"gCO\textsubscript{2}eq")


def header(
    path: Path,
    libraries: list[str],
    what: str,
    source: str,
    colours: list[str] | None = None,
) -> list[str]:
    """The comment block every generated file opens with.

    It exists because the first thing that goes wrong is a missing package:
    without pgfplots, LaTeX does not know `tikzpicture` and typesets the file
    as text instead of drawing it, which looks like the figure "not working"
    rather than like a preamble problem."""
    lines = [
        f"% {what}, generated by",
        f"% federation-tests/scripts/{source} -- edit freely.",
        "%",
        r"% 1. In the PREAMBLE of the main file, before \begin{document}:",
        r"%      \usepackage{pgfplots}",
    ]
    lines += [f"%      \\usepgfplotslibrary{{{library}}}" for library in libraries]
    lines += [
        r"%      \pgfplotsset{compat=1.18}",
        "%    Without them LaTeX does not know tikzpicture and prints this file",
        "%    as text instead of drawing it.",
        "%",
        f"% 2. Put this file next to the chapter (say figures/{path.name}) and",
        "%    include it, rather than pasting it in: regenerating the figure then",
        "%    costs nothing.",
        "%",
        r"%      \begin{figure}[htbp]",
        r"%        \centering",
        f"%        \\input{{figures/{path.name}}}",
        r"%        \caption{...}",
        f"%        \\label{{fig:{path.stem.replace('_', '-')}}}",
        r"%      \end{figure}",
        "%",
    ]
    wanted = colours if colours is not None else list(COLOURS)
    lines += [f"\\definecolor{{{name}}}{{HTML}}{{{COLOURS[name]}}}" for name in wanted]
    return lines


def _wrap(pairs: list[str], per_line: int = 6) -> list[str]:
    """Wraps a coordinate list so the generated file stays readable."""
    return [
        "    " + " ".join(pairs[start : start + per_line]) for start in range(0, len(pairs), per_line)
    ]


def _coordinates(frame: pd.DataFrame, x_column: str, y_column: str) -> list[str]:
    """The coordinate list of one series."""
    return _wrap(
        [
            f"({x:.6g},{y:.6g})"
            for x, y in zip(frame[x_column], frame[y_column])
            if pd.notna(x) and pd.notna(y)
        ]
    )


def _step_points(xs: list[float], ys: list[float]) -> list[tuple[float, float]]:
    """The same staircase `const plot` draws, as explicit vertices: each value
    is held until the next point, then jumps."""
    points: list[tuple[float, float]] = []
    for index, (x, y) in enumerate(zip(xs, ys)):
        points.append((x, y))
        if index + 1 < len(xs):
            points.append((xs[index + 1], y))
    return points


def _band_polygon(band: pd.DataFrame) -> list[str]:
    """The shaded range as one closed outline: up along the ceiling, back along
    the floor.

    Drawn this way rather than with the `fillbetween` library because the
    staircase is already ours to describe, so the figure needs no extra package
    in the preamble -- and a preamble that is missing one is exactly how a
    figure ends up with its dashed edges drawn and the fill silently absent.
    TikZ closes a filled path by itself, so the left edge needs no vertex."""
    edges = band.dropna(subset=["floor", "ceiling"])
    xs = [float(v) for v in edges["elapsed_minutes"]]
    ceiling = _step_points(xs, [float(v) for v in edges["ceiling"]])
    floor = _step_points(xs, [float(v) for v in edges["floor"]])
    outline = ceiling + floor[::-1]
    return _wrap([f"({x:.6g},{y:.6g})" for x, y in outline])


def _label(text: str, limit: int = 40) -> tuple[str, bool]:
    """A label for an axis, broken over two lines when it is long enough to
    steal width from the figure. Returns the LaTeX and whether it was broken,
    since a broken label also needs `align` set on its style."""
    if len(text) <= limit:
        return escape(text), False
    # Break at the space closest to the middle, so neither line is a stub.
    middle = len(text) // 2
    spaces = [i for i, character in enumerate(text) if character == " "]
    if not spaces:
        return escape(text), False
    cut = min(spaces, key=lambda i: abs(i - middle))
    return escape(text[:cut]) + r"\\" + escape(text[cut + 1 :]), True


def write_line_chart(
    path: Path,
    *,
    series: list[tuple[str, str, pd.DataFrame, str]],
    band: pd.DataFrame | None,
    band_label: str,
    x_label: str,
    y_label: str,
    log_scale: bool = False,
    bottom: float | None = None,
    source: str,
) -> None:
    """Writes one of the two comparison charts as pgfplots source.

    `series` is (label, colour name, frame, value column); every frame carries
    the elapsed minutes in `elapsed_minutes`. `band` carries `floor` and
    `ceiling` on the same axis, or is None when the run had no second input to
    build a range from. `source` is the calling script, named in the comment
    header so a file found on its own says where to regenerate it.
    """
    shaded = band is not None and not band.empty
    lines = header(
        path,
        [],
        "Policy comparison over time",
        source,
        [colour for _, colour, _, _ in series]
        + (["phaseFloor", "phaseBand"] if shaded else []),
    )
    y_text, y_broken = _label(y_label)
    lines += [
        r"\begin{tikzpicture}",
        r"\begin{axis}[",
        r"    width=0.95\textwidth, height=7cm,",
        f"    xlabel={{{escape(x_label)}}},",
        f"    ylabel={{{y_text}}},",
        "    xmin=0,",
    ]
    if y_broken:
        # A two-line label is a node with a line break, and a node only honours
        # the break once it is told how to align the lines.
        lines.append("    ylabel style={align=center},")
    if log_scale:
        lines.append("    ymode=log, log basis y=10,")
        if bottom is not None:
            lines.append(f"    ymin={bottom:.6g},")
    else:
        lines.append("    ymin=0,")
    lines += [
        "    grid=major, grid style={gray!25, dashed},",
        "    legend style={at={(0.5,1.03)}, anchor=south, legend columns=-1, draw=none},",
        "    legend cell align=left,",
        "]",
    ]

    if shaded:
        # Drawn first, so the curves sit on top of it: the filled outline, then
        # the two edges dashed over it.
        lines.append(r"\addplot[draw=none, fill=phaseBand, fill opacity=0.45, forget plot]")
        lines.append("  coordinates {")
        lines += _band_polygon(band)
        lines.append("  };")
        for edge in ("floor", "ceiling"):
            lines.append(
                "\\addplot[const plot, draw=phaseFloor, dashed, line width=0.4pt, "
                "forget plot] coordinates {"
            )
            lines += _coordinates(band.dropna(subset=["floor", "ceiling"]), "elapsed_minutes", edge)
            lines.append("};")

    for label, colour, frame, column in series:
        if frame is None or frame.empty:
            continue
        lines.append(f"\\addplot[const plot, draw={colour}, line width=1pt] coordinates {{")
        lines += _coordinates(frame, "elapsed_minutes", column)
        lines.append("};")
        lines.append(f"\\addlegendentry{{{escape(label)}}}")

    if shaded:
        # The band is a `forget plot`, so its legend entry is added by hand.
        lines.append(
            r"\addlegendimage{area legend, fill=phaseBand, fill opacity=0.45, "
            r"draw=phaseFloor, dashed}"
        )
        lines.append(f"\\addlegendentry{{{escape(band_label)}}}")

    lines += [r"\end{axis}", r"\end{tikzpicture}"]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
